### ISSUE TITLE
[BUG] - Open accordion heeft max-height restrictie

### ISSUE THREAD

**Issue by SBylemans** [milieuinfo/webcomponent-vl-ui-accordion#115]
**Omschrijf het probleem**
De styling van AIV bevat een max-height restrictie op een open accordion.

```
.js .js-vl-accordion--open > .vl-accordion__content {
  visibility: visible;
  max-height: 1000vh;
  overflow: visible;
  transition: max-height .3s, overflow 0s .3s
}
```

Hierdoor komt de footer soms in het midden van ons scherm.

**Hoe te reproduceren**
Een accordion met veel content en een footer onderaan zetten.

**Gewenst gedrag**
Footer onderaan accordion content.

**Screenshots**
![image](https://user-images.githubusercontent.com/5698858/94444827-0598d380-01a7-11eb-9324-e0391f5a1d06.png)
![image](https://user-images.githubusercontent.com/5698858/94444862-0df10e80-01a7-11eb-84dd-bb16d18af23e.png)

**Omgeving (gelieve aan te vullen):**
 - Versie component 3.0.9

**Extra info**
De max-height restrictie veranderen naar 100% ipv 1000vh lost het probleem normaal op.

Een voorbeeld van de issue is hier te zien: https://dsi-oefen.omgeving.vlaanderen.be/dossier-detail/ccdbb3c7-fe35-4ca6-9478-510349b98f35 -> open accordion onderaan scherm en scroll naar beneden.

**Comment by coemans** [comment]
PR #878 aangemaakt bij AIV met change event uitbreiding.

**Comment by coemans** [comment]
@SBylemans indien PR goedgekeurd wordt, zal bij de volgende huisstijl upgrade dit issue opgelost en gesloten worden. Als jullie de feature vroeger nodig hebben, kan de code op ons niveau vervroegd toegepast worden. Graag dan een seintje.

**Comment by coemans** [comment]
PR is niet goedgekeurd, 100% kan niet toegepast worden omdat dit de animatie zou breken. Compromis is geworden om `overflow-y: scroll` toe te passen. Wanneer er meer dan 1.000vh nodig is, zouden er vragen gesteld kunnen worden over het design en gebruik van de accordion. Eventueel kan dit bekeken worden, maar als alternatief zal de content in de volgende huisstijl upgrade scrollable worden.
