### ISSUE TITLE
[BUG] - Combinatie van vl-accordion met vl-info-tile breekt openen functionaliteit

### ISSUE THREAD

**Issue by pharacyde** [milieuinfo/webcomponent-vl-ui-accordion#128]
**Omschrijf het probleem**
integratie probleem accordion met info tile

**Hoe te reproduceren**
De volgorde van imports is van belang. Als je eerst info tile importeert dan werkt accordion niet. 
```
import 'vl-ui-info-tile';
import 'vl-ui-accordion';
```
Voorlopig hebben we de workaround dat vl-ui-accordion altijd toegevoegd wordt als import voor de vl-ui-tile import. Ook al wordt de accordion niet gebruikt in de component. Dit om zeker te zijn dat accordion voor info tile geimporteerd wordt. 

```
import 'vl-ui-accordion';
import 'vl-ui-info-tile';
```
 
**Gewenst gedrag**
Volgorde van import zou geen effect mogen hebben, daar je niet op voorhand kunt voorspellen welke componenten welke imports gaan doen.

**Comment by stefanborghys** [comment]
We merken op het voortoets project een gelijkaardig probleem. Wanneer we de info-tile gebruiken in de accordion faalt de toggle functionaliteit deels in de info-tile. Je kan die dan wel togglen via het pijltje of door naast de titel te klikken maar niet meer door op de titel te klikken.

**Comment by stefanborghys** [comment]
PR met reproductie testen klaargezet
